kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimeStamp: null
  name: pod-readers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: users:user3
